#define FLOW_TAP_TERM 100
#define CHORDAL_HOLD
#define USB_SUSPEND_WAKEUP_DELAY 0
#define SERIAL_NUMBER "NKrmd/ga5KG0"
#define LAYER_STATE_8BIT
#define COMBO_COUNT 1

#define NAVIGATOR_TRACKBALL_CPI 25
#define NAVIGATOR_SCROLL_DIVIDER 50

#define AUTOMOUSE_LAYER 3
#define AUTOMOUSE_THRESHOLD 10
#define AUTOMOUSE_ONESHOT
#define AUTOMOUSE_SCROLL_THRESHOLD AUTOMOUSE_THRESHOLD / NAVIGATOR_SCROLL_DIVIDER
#define RGB_MATRIX_STARTUP_SPD 60

